# syntax=docker/dockerfile:1

## Build
FROM golang:1.19-buster AS build

WORKDIR /app

COPY . ./
RUN go mod download

RUN cd cli && go build -o cli

## Deploy
FROM golang:1.19-buster

WORKDIR /build
COPY --from=build /app/cli/cli /build/cli/cli
COPY --from=build /app/data/ /build/data
