apiVersion: v1
data:
  DB_HOST: 127.0.0.1:5432
  DD_ENV: prod
kind: ConfigMap
metadata:
  name: iban-service-2d9c79db6b
---
apiVersion: v1
kind: Secret
metadata:
  name: iban-service-8226t8dd99
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: iban-api-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    app: iban-service
    component: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iban-service
    component: api
  name: iban-api-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iban-service
      component: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        ad.datadoghq.com/app.logs: '[{"source":"logstash","service":"iban-api-service"}]'
      labels:
        app: iban-service
        component: api
    spec:
      containers:
      - command:
        - sh
        - -c
        - ./iban
        envFrom:
        - configMapRef:
            name: iban-service-2d9c79db6b
        - secretRef:
            name: iban-service-8226t8dd99
        image: iban/iban-go-service:latest
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        name: app
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 110m
            memory: 64Mi
      - command:
        - /cloud_sql_proxy
        - --dir=/cloudsql
        - -instances=pfc:europe-north1:prod-common-postgresql-europe-north1=tcp:5432
        - -credential_file=/secrets/cloudsql/credentials.json
        name: cloud-sql-proxy
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: iban-api-service
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: iban-service
      component: api
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: iban-api-service
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iban-api-service
  targetCPUUtilizationPercentage: 90
