apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: iban-api-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iban-api-service
  minReplicas: 2
  maxReplicas: 5
